/* This file is generated by zits. Do not edit manually */

import {
/** Types */
HoloHash,
AgentPubKey,
DnaHash,
WasmHash,
EntryHash,
ActionHash,
AnyDhtHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
HoloHashed,
NetworkInfo,
FetchQueueInfo,
/** Action */
SignedActionHashed,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** Capabilities */
CapSecret,
CapClaim,
ZomeCallCapGrant,
CapAccess,
CapGrant,
GrantedFunctionsType,
/** CounterSigning */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** DhtOps */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** Entry */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** Record */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** admin types */
InstalledAppInfoStatus,
StemCell,
Cell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';

import {
/** Common */
DhtOpHashB64,
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

export interface DmPacket {
  from: AgentPubKey
  dm: DirectMessageProtocol
}

export enum DirectMessageProtocolType {
	Failure = 'Failure',
	Success = 'Success',
	Mail = 'Mail',
	Ack = 'Ack',
	Chunk = 'Chunk',
	FileManifest = 'FileManifest',
	RequestChunk = 'RequestChunk',
	RequestManifest = 'RequestManifest',
	UnknownEntry = 'UnknownEntry',
	Ping = 'Ping',
}
export type DirectMessageProtocolVariantFailure = {Failure: string}
export type DirectMessageProtocolVariantSuccess = {Success: string}
export type DirectMessageProtocolVariantMail = {Mail: MailMessage}
export type DirectMessageProtocolVariantAck = {Ack: AckMessage}
export type DirectMessageProtocolVariantChunk = {Chunk: FileChunk}
export type DirectMessageProtocolVariantFileManifest = {FileManifest: FileManifest}
export type DirectMessageProtocolVariantRequestChunk = {RequestChunk: EntryHash}
export type DirectMessageProtocolVariantRequestManifest = {RequestManifest: EntryHash}
export type DirectMessageProtocolVariantUnknownEntry = {UnknownEntry: null}
export type DirectMessageProtocolVariantPing = {Ping: null}
export type DirectMessageProtocol = 
 | DirectMessageProtocolVariantFailure | DirectMessageProtocolVariantSuccess | DirectMessageProtocolVariantMail | DirectMessageProtocolVariantAck | DirectMessageProtocolVariantChunk | DirectMessageProtocolVariantFileManifest | DirectMessageProtocolVariantRequestChunk | DirectMessageProtocolVariantRequestManifest | DirectMessageProtocolVariantUnknownEntry | DirectMessageProtocolVariantPing;

export interface MailMessage {
  mail: Mail
  outmail_eh: EntryHash
  mail_signature: Signature
}

export interface AckMessage {
  outmail_eh: EntryHash
  ack_signature: Signature
}

export type FindManifestOutput = FileManifest | null;

export type ZomeManifestVec = FileManifest[];

export interface GetMissingAttachmentsInput {
  from: AgentPubKey
  inmail_ah: ActionHash
}

export interface GetMissingChunksInput {
  from: AgentPubKey
  manifest_eh: EntryHash
}

export interface WriteManifestInput {
  data_hash: string
  filename: string
  filetype: string
  orig_filesize: number
  chunks: EntryHash[]
}

export interface HandleItem {
  name: string
  agentId: AgentPubKey
  handle_eh: EntryHash
}

export interface CommitPendingAckInput {
  outack_eh: EntryHash
  outmail_eh: EntryHash
  original_sender: AgentPubKey
}

export type DeleteMailOutput = ActionHash | null;

export type GetMailOutput = InMail | OutMail | null;

export interface SendMailInput {
  subject: string
  payload: string
  reply_of?: ActionHash
  to: AgentPubKey[]
  cc: AgentPubKey[]
  bcc: AgentPubKey[]
  manifest_address_list: ActionHash[]
}

export interface CommitPendingMailInput {
  mail: PendingMail
  outmail_eh: EntryHash
  destination: AgentPubKey
}

export enum SignalProtocolType {
	ReceivedMail = 'ReceivedMail',
	ReceivedAck = 'ReceivedAck',
	ReceivedFile = 'ReceivedFile',
}
export type SignalProtocolVariantReceivedMail = {ReceivedMail: MailItem}
export type SignalProtocolVariantReceivedAck = {ReceivedAck: ReceivedAck}
export type SignalProtocolVariantReceivedFile = {ReceivedFile: FileManifest}
export type SignalProtocol = 
 | SignalProtocolVariantReceivedMail | SignalProtocolVariantReceivedAck | SignalProtocolVariantReceivedFile;

export interface ReceivedAck {
  from: AgentPubKey
  for_mail: ActionHash
}

/** Entry representing a file chunk. */
export interface FileChunk {
  data_hash: string
  chunk_index: number
  chunk: string
}

/**
 * Entry representing a file in chunks.
 * All chunks must be committed beforehand.
 */
export interface FileManifest {
  data_hash: string
  filename: string
  filetype: string
  orig_filesize: number
  chunks: EntryHash[]
  content?: string
}

/** Entry representing the username of an Agent */
export interface Handle {
  name: string
}

export enum SnapmailEntryType {
	PubEncKey = 'PubEncKey',
	Handle = 'Handle',
	InMail = 'InMail',
	OutMail = 'OutMail',
	OutAck = 'OutAck',
	InAck = 'InAck',
	PendingMail = 'PendingMail',
	PendingAck = 'PendingAck',
	DeliveryConfirmation = 'DeliveryConfirmation',
	FileChunk = 'FileChunk',
	FileManifest = 'FileManifest',
}
export type SnapmailEntryVariantPubEncKey = {PubEncKey: PubEncKey}
export type SnapmailEntryVariantHandle = {Handle: Handle}
export type SnapmailEntryVariantInMail = {InMail: InMail}
export type SnapmailEntryVariantOutMail = {OutMail: OutMail}
export type SnapmailEntryVariantOutAck = {OutAck: OutAck}
export type SnapmailEntryVariantInAck = {InAck: InAck}
export type SnapmailEntryVariantPendingMail = {PendingMail: PendingMail}
export type SnapmailEntryVariantPendingAck = {PendingAck: PendingAck}
export type SnapmailEntryVariantDeliveryConfirmation = {DeliveryConfirmation: DeliveryConfirmation}
export type SnapmailEntryVariantFileChunk = {FileChunk: FileChunk}
export type SnapmailEntryVariantFileManifest = {FileManifest: FileManifest}
export type SnapmailEntry = 
 | SnapmailEntryVariantPubEncKey | SnapmailEntryVariantHandle | SnapmailEntryVariantInMail | SnapmailEntryVariantOutMail | SnapmailEntryVariantOutAck | SnapmailEntryVariantInAck | SnapmailEntryVariantPendingMail | SnapmailEntryVariantPendingAck | SnapmailEntryVariantDeliveryConfirmation | SnapmailEntryVariantFileChunk | SnapmailEntryVariantFileManifest;

/** List of all Link kinds handled by this Zome */
export type LinkKind =
  | {Members: null} | {AckInbox: null} | {MailInbox: null} | {Handle: null} | {Pending: null} | {Pendings: null} | {EncKey: null};

/** Entry for a received Acknowledgement Receipt */
export interface DeliveryConfirmation {
  /** EntryHash to OutMail or OutAck on same chain */
  package_eh: EntryHash
  recipient: AgentPubKey
}

/** Entry for a received Acknowledgement Receipt */
export interface InAck {
  outmail_eh: EntryHash
  from: AgentPubKey
  /** Signed outmail_eh */
  from_signature: Signature
}

/** Entry representing a received mail. */
export interface InMail {
  mail: Mail
  date_received: number
  outmail_eh: EntryHash
  from: AgentPubKey
  from_signature: Signature
}

/** Possible states of an InMail entry */
export type InMailState =
  | {Unacknowledged: null} | {AckUnsent: null} | {AckPending: null} | {AckDelivered: null} | {Deleted: null};

/** State of a single delivery of a mail or ack to a unique recipient */
export type DeliveryState =
  | {Unsent: null} | {Pending: null} | {Delivered: null};

/** Possible states of an OutMail entry */
export type OutMailState =
  | {Unsent: null} | {AllSent: null} | {AllReceived: null} | {AllAcknowledged: null} | {Deleted: null};

export enum MailStateType {
	In = 'In',
	Out = 'Out',
}
export type MailStateVariantIn = {In: InMailState}
export type MailStateVariantOut = {Out: OutMailState}
export type MailState = 
 | MailStateVariantIn | MailStateVariantOut;

export interface MailItem {
  ah: ActionHash
  author: AgentPubKey
  mail: Mail
  state: MailState
  bcc: AgentPubKey[]
  date: number
  /** UI Things */
  reply?: ActionHash
  reply_of?: ActionHash
  status?: string
}

export type RecipientKind =
  | {TO: null} | {CC: null} | {BCC: null};

/**
 * Core content of all *Mail Entries
 * Mail can have Zero public recipient (but must have at least one public or private recipient)
 */
export interface Mail {
  date_sent: number
  subject: string
  payload: string
  to: AgentPubKey[]
  cc: AgentPubKey[]
  attachments: AttachmentInfo[]
}

/** Metadata for a mail attachment */
export interface AttachmentInfo {
  manifest_eh: EntryHash
  data_hash: string
  filename: string
  filetype: string
  orig_filesize: number
}

/** Entry for an Acknowledgement Receipt of a Mail authored by this agent */
export interface OutAck {
  inmail_eh: EntryHash
}

/** Entry representing an authored mail. It is private. */
export interface OutMail {
  mail: Mail
  reply_of?: ActionHash
  bcc: AgentPubKey[]
}

/** Entry representing an AcknowldegmentReceipt on the DHT waiting to be received */
export interface PendingAck {
  outmail_eh: EntryHash
  /** Signed outmail_eh */
  from_signature: Signature
}

/**
 * Entry representing a mail on the DHT waiting to be received by recipient.
 * The recipient is the agentId where the entry is linked from.
 * The mail is encrypted with the recipient's public encryption key.
 */
export interface PendingMail {
  encrypted_mail: unknown
  outmail_eh: EntryHash
  from_signature: Signature
}

/** Entry representing the Public Encryption Key of an Agent */
export interface PubEncKey {
  value: Uint8Array
}
