/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "snapmail" */
export const snapmailFunctionNames: FunctionName[] = [
	"entry_defs",
	"init_caps",



	"receive_dm",
	"find_manifest",
	"get_all_manifests",
	"get_chunk",
	"get_manifest",
	"get_missing_attachments",
	"get_missing_chunks",
	"write_chunk",
	"write_manifest",
	"get_enc_key",
	"get_my_enc_key",
	"test_encryption",
	"find_agent",
	"get_all_handles",
	"get_handle",
	"get_my_handle",
	"get_my_handle_history",
	"ping_agent",
	"create_empty_handle",
	"set_handle",
	"acknowledge_mail",
	"commit_pending_ack",
	"commit_confirmation",
	"check_ack_inbox",
	"check_mail_inbox",
	"delete_mail",
	"get_all_mails",
	"get_all_unacknowledged_inmails",
	"get_mail",
	"get_outmail_state",
	"get_outmail_delivery_state",
	"has_ack_been_delivered",
	"is_outack_sent",
	"request_acks",
	"resend_outacks",
	"resend_outmails",
	"commit_inmail",
	"commit_pending_mail",
	"send_mail",];


/** Generate tuple array of function names with given zomeName */
export function generateSnapmailZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   let fns: [ZomeName, FunctionName][] = [];
   for (const fn of snapmailFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "snapmail" */
export const snapmailZomeFunctions: [ZomeName, FunctionName][] = generateSnapmailZomeFunctionsArray("snapmail");
