/* This file is generated by zits. Do not edit manually */

import {CAN_DM, DIRECTORY_ANCHOR, DIRECT_SEND_CHUNK_TIMEOUT_MS, DIRECT_SEND_TIMEOUT_MS, REMOTE_ENDPOINT, SNAPMAIL_DEFAULT_COORDINATOR_ZOME_NAME, SNAPMAIL_DEFAULT_INTEGRITY_ZOME_NAME, SNAPMAIL_DEFAULT_ROLE_NAME, DeliveryState, DirectMessageProtocol, InMailState, MailState, OutMailState, RecipientKind, SignalProtocol, SnapmailEntry, AckMessage, AttachmentInfo, CommitPendingAckInput, CommitPendingMailInput, DeliveryConfirmation, DmPacket, FileChunk, FileManifest, GetMailOutput, GetMissingAttachmentsInput, GetMissingChunksInput, Handle, HandleItem, InAck, InMail, Mail, MailItem, MailMessage, OutAck, OutMail, PendingAck, PendingMail, PubEncKey, SendMailInput, SnapmailProperties, SnapmailSignal, WriteManifestInput, } from './snapmail.types';
import {
WebsocketConnectionOptions,
/** types.ts */
//HoloHash,
//AgentPubKey,
//DnaHash,
//WasmHash,
//EntryHash,
//ActionHash,
//AnyDhtHash,
//ExternalHash,
KitsuneAgent,
KitsuneSpace,
HoloHashB64,
AgentPubKeyB64,
DnaHashB64,
WasmHashB64,
EntryHashB64,
ActionHashB64,
AnyDhtHashB64,
InstalledAppId,
Signature,
CellId,
DnaProperties,
RoleName,
InstalledCell,
Timestamp,
Duration,
HoloHashed,
NetworkInfo,
FetchPoolInfo,
/** hdk/action.ts */
SignedActionHashed,
RegisterAgentActivity,
ActionHashed,
ActionType,
Action,
NewEntryAction,
Dna,
AgentValidationPkg,
InitZomesComplete,
CreateLink,
DeleteLink,
OpenChain,
CloseChain,
Update,
Delete,
Create,
/** hdk/capabilities.ts */
CapSecret,
CapClaim,
GrantedFunctionsType,
GrantedFunctions,
ZomeCallCapGrant,
CapAccessType,
CapAccess,
CapGrant,
///** hdk/countersigning.ts */
//CounterSigningSessionData,
//PreflightRequest,
//CounterSigningSessionTimes,
//ActionBase,
//CounterSigningAgents,
//PreflightBytes,
//Role,
//CountersigningAgentState,
/** hdk/dht-ops.ts */
DhtOpType,
DhtOp,
getDhtOpType,
getDhtOpAction,
getDhtOpEntry,
getDhtOpSignature,
/** hdk/entry.ts */
EntryVisibility,
AppEntryDef,
EntryType,
EntryContent,
Entry,
/** hdk/record.ts */
Record as HcRecord,
RecordEntry as HcRecordEntry,
/** hdk/link.ts */
AnyLinkableHash,
ZomeIndex,
LinkType,
LinkTag,
RateWeight,
RateBucketId,
RateUnits,
Link,
/** api/admin/types.ts */
InstalledAppInfoStatus,
DeactivationReason,
DisabledAppReason,
StemCell,
ProvisionedCell,
ClonedCell,
CellType,
CellInfo,
AppInfo,
MembraneProof,
FunctionName,
ZomeName,
ZomeDefinition,
IntegrityZome,
CoordinatorZome,
DnaDefinition,
ResourceBytes,
ResourceMap,
CellProvisioningStrategy,
CellProvisioning,
DnaVersionSpec,
DnaVersionFlexible,
AppRoleDnaManifest,
AppRoleManifest,
AppManifest,
AppBundle,
AppBundleSource,
NetworkSeed,
ZomeLocation,
   } from '@holochain/client';


/// Simple Hashes
type AgentArray = Uint8Array;
type DnaArray = Uint8Array;
type WasmArray = Uint8Array;
type EntryArray = Uint8Array;
type ActionArray = Uint8Array;
type AnyDhtArray = Uint8Array;
type AnyLinkableArray = Uint8Array;
type ExternalArray = Uint8Array;

import {
/** Common */
DhtOpHashB64,
//DnaHashB64, (duplicate)
//AnyDhtHashB64, (duplicate)
DhtOpHash,
/** DnaFile */
DnaFile,
DnaDef,
Zomes,
WasmCode,
/** entry-details */
EntryDetails,
RecordDetails,
Details,
DetailsType,
EntryDhtStatus,
/** Validation */
ValidationStatus,
ValidationReceipt,
   } from '@holochain-open-dev/core-types';

import {ZomeProxy} from '@ddd-qc/lit-happ';
import {snapmailFunctionNames} from './snapmail.fn';
import {SnapmailUnitEnum, SnapmailLinkType} from './snapmail.integrity';

/**
 *
 */
export class SnapmailProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "snapmail";
  static readonly FN_NAMES = snapmailFunctionNames;
  static readonly ENTRY_TYPES = Object.values(SnapmailUnitEnum);
  static readonly LINK_TYPES = Object.values(SnapmailLinkType);
 
  async findManifest(dataHash: string): Promise<FileManifest | null> {
    return this.call('find_manifest', dataHash);
  }

  async getAllManifests(): Promise<FileManifest[]> {
    return this.call('get_all_manifests', null);
  }

  async getChunk(chunkEh: EntryArray): Promise<string> {
    return this.call('get_chunk', chunkEh);
  }

  async getManifest(manifestAddress: AnyDhtArray): Promise<FileManifest> {
    return this.call('get_manifest', manifestAddress);
  }

  async getMissingAttachments(input: GetMissingAttachmentsInput): Promise<number> {
    return this.call('get_missing_attachments', input);
  }

  async getMissingChunks(input: GetMissingChunksInput): Promise<number> {
    return this.call('get_missing_chunks', input);
  }

  async writeChunk(inputChunk: FileChunk): Promise<EntryArray> {
    return this.call('write_chunk', inputChunk);
  }

  async writeManifest(input: WriteManifestInput): Promise<ActionArray> {
    return this.call('write_manifest', input);
  }

  async findAgent(handle: string): Promise<AgentArray[]> {
    return this.call('find_agent', handle);
  }

  async getAllHandles(): Promise<HandleItem[]> {
    return this.call('get_all_handles', null);
  }

  async getHandle(agentId: AgentArray): Promise<string> {
    return this.call('get_handle', agentId);
  }

  async getMyHandle(): Promise<string> {
    return this.call('get_my_handle', null);
  }

  async getMyHandleHistory(initialHandleAddress: ActionArray): Promise<string[]> {
    return this.call('get_my_handle_history', initialHandleAddress);
  }

  async pingAgent(destination: AgentArray): Promise<boolean> {
    return this.call('ping_agent', destination);
  }

  async createEmptyHandle(): Promise<ActionArray> {
    return this.call('create_empty_handle', null);
  }

  async setHandle(newUsername: string): Promise<ActionArray> {
    return this.call('set_handle', newUsername);
  }

  async acknowledgeMail(inmailAh: ActionArray): Promise<EntryArray> {
    return this.call('acknowledge_mail', inmailAh);
  }

  async commitPendingAck(input: CommitPendingAckInput): Promise<ActionArray> {
    return this.call('commit_pending_ack', input);
  }

  async checkAckInbox(): Promise<EntryArray[]> {
    return this.call('check_ack_inbox', null);
  }

  async checkMailInbox(): Promise<ActionArray[]> {
    return this.call('check_mail_inbox', null);
  }

  async deleteMail(ah: ActionArray): Promise<ActionArray | null> {
    return this.call('delete_mail', ah);
  }

  async getAllMails(): Promise<MailItem[]> {
    return this.call('get_all_mails', null);
  }

  async getAllUnacknowledgedInmails(): Promise<ActionArray[]> {
    return this.call('get_all_unacknowledged_inmails', null);
  }

  async getMail(ah: ActionArray): Promise<GetMailOutput> {
    return this.call('get_mail', ah);
  }

  async getOutmailState(outmailAh: ActionArray): Promise<OutMailState> {
    return this.call('get_outmail_state', outmailAh);
  }

  async getOutmailDeliveryState(outmailAh: ActionArray): Promise<Record<string, AgentArray>> {
    return this.call('get_outmail_delivery_state', outmailAh);
  }

  async hasAckBeenDelivered(inmailAh: ActionArray): Promise<boolean> {
    return this.call('has_ack_been_delivered', inmailAh);
  }

  async isOutackSent(outackAh: ActionArray): Promise<boolean> {
    return this.call('is_outack_sent', outackAh);
  }

  async requestAcks(): Promise<ActionArray[]> {
    return this.call('request_acks', null);
  }

  async resendOutacks(): Promise<ActionArray[]> {
    return this.call('resend_outacks', null);
  }

  async resendOutmails(): Promise<ActionArray[]> {
    return this.call('resend_outmails', null);
  }

  async sendMail(input: SendMailInput): Promise<ActionArray> {
    return this.call('send_mail', input);
  }

  async testEncryption(recipient: AgentArray): Promise<void> {
    return this.call('test_encryption', recipient);
  }
}
