name: build-webhapps

on:
  workflow_call:

jobs:
  build-webhapps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # Download rsm repo
      - name: Download rsm
        shell: bash
        run: |
          npm run setup
      # Install hash-zome binary
      - name: Hash Zome Install
        run: |
          npm run install:hash-zome
      # Build happ
      - name: Build happ
        shell: bash
        run: |
          ./scripts/npm/dist-dna.sh
      # Hash zome
      - name: Hash zome
        shell: bash
        run: |
          npm run hash-zome
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # Build webapp
      - name: Build webapp
        run: |
          npm run build:devtest
      # Package web-happ
      - name: Package web-happ
        run: |
          npm run package -w webapp
      # build we-applet
      - name: build we-applet
        shell: bash
        run: |
          npm run build -w we-applet
      # Package we-applet
      - name: Package we-applet
        shell: bash
        run: |
          npm run package -w we-applet
      # List submodules
      - name: List submodules
        continue-on-error: true
        run: ls
        working-directory: submodules
      # Regroup artifacts
      - name: Regroup artifacts
        run: |
          mkdir -p artifacts
          cp electron/bin/model_zome_hash.txt ./artifacts          
          cp submodules/snapmail-rsm/target/wasm32-unknown-unknown/release/snapmail_model.wasm ./artifacts
          cp submodules/snapmail-rsm/target/wasm32-unknown-unknown/release/snapmail.wasm ./artifacts                 
          cp webapp/webhapp.workdir/snapmail.webhapp ./artifacts
          cp we-applet/webhapp.workdir/snapmail-we_applet.webhapp ./artifacts
          cp we-applet/snapmail-we_applet-ui.zip ./artifacts
          cp webapp/snapmail-web-ui.zip ./artifacts
      # List uploaded files
      - name: List uploaded files
        run: ls -R
        working-directory: ./artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@master
        with:
          name: all-happ-artifact
          path: artifacts/
