name: build-dna

on:
  workflow_call:

jobs:
  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # Install hash-zome binary
      - name: Hash Zome Install
        run: |
          npm run hash-zome-install
      # Download snapmail repos (rsm & ui)
      - name: Download snapmail-ui repo
        shell: bash
        run: |
          npm run setup
      # Build dna
      - name: Build DNA
        run: |
          npm run dna-pack
      # Hash Zome
      - name: Hash Zome
        run: |
          npm run hash-zome
      # "upload" dna as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-artifact
          path: bin/snapmail.dna
      # "upload" happ as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-happ-artifact
          path: bin/snapmail.happ
      # "upload" zome_hash as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: zome-artifact
          path: bin/zome_hash.txt
