name: build-dna

on:
  workflow_call:

jobs:
  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run ci:hc-install
      # Install hash-zome binary
      - name: Hash Zome Install
        run: |
          npm run install:hash-zome
      # Download rsm repo
      - name: Download rsm
        shell: bash
        run: |
          npm run setup
      # Build happ
      - name: Build happ
        run: |
          npm run build:happ
      # list uploads
      - name: list uploads
        continue-on-error: true
        run: ls
        working-directory: submodules
      # "upload" dna as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-dna-artifact
          path: submodules/snapmail.dna
      # "upload" happ as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-happ-artifact
          path: submodules/snapmail.happ
      # "upload" zome_hash as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: model-hash-artifact
          path: electron/bin/model_zome_hash.txt
