name: Release arm64

on:

jobs:
  # the create-release would be used once we want to create a specific release based on if the commit has a tag
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run dna-install
      # Download other snapmail repos
      - name: Download other snapmail repos
        shell: bash # important because this runs shell scripts
        run: |
          npm run dna-setup
      # # build dna
      - name: Build DNA
        run: |
          npm run dna-pack
      # "upload" dna as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-artifact
          path: dna/snapmail.dna

  # upload the app package for each target os
  upload-assets:
    needs: build-dna
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 arm64
    steps:
      - uses: actions/checkout@v2
      # rm the dna files from repository
      - name: clearing precompiled dna files
        run: |
          rm dna/*.dna
      - uses: actions/download-artifact@master
        with:
          name: snapmail-artifact
          path: dna
      - name: list downloads
        run: ls -R
        working-directory: dna
      # Install nodejs dependencies
      - uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: aarch64
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run web-install
          npm run build-prod
          npm run dist-build
          ls out
          gh release upload "${GITHUB_REF#refs/tags/}" "out/Snapmail-0.1.5.tar.gz" --clobber
