name: Release x64

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  # the create-release would be used once we want to create a specific release based on if the commit has a tag
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          SNAPMAIL_VERSION: 0.1.5
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-dna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # # install hc tool
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run dna-install
      # Download other snapmail repos
      - name: Download other snapmail repos
        shell: bash # important because this runs shell scripts
        run: |
          npm run dna-setup
      # # build dna
      - name: Build DNA
        run: |
          npm run dna-pack
      # "upload" dna as build artifact
      - uses: actions/upload-artifact@master
        with:
          name: snapmail-artifact
          path: dna/snapmail.dna

  # upload the app package for each target os
  upload-assets:
    needs: build-dna
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Add Windows certificate
      - name: Add Windows certificate
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'win-certificate.pfx'
          encodedString: ${{ secrets.CERTIFICATE_WINDOWS_PFX }}
      # rm the dna files from repository
      - name: clearing precompiled dna files
        run: |
          rm dna/*.dna
      # Download previously uploaded artifacts and display them in logs
      - uses: actions/download-artifact@master
        with:
          name: snapmail-artifact
          path: dna
      - name: list downloads
        run: ls -R
        working-directory: dna
      # Download other snapmail repos
      - name: Download other snapmail repos
        shell: bash # important because this runs shell scripts
        run: |
          npm run dna-setup
      # depending on the windows command (when we are ready to build for it), may have to check which os currently on
      - name: Install nodejs dependencies
        run: |
          npm install
          npm run web-install
      # build snapmail-ui
      - name: build snapmail-ui
        shell: bash
        run: |
          npm run build-prod
      # build holochain and lair
      - name: build holochain and lair
        shell: bash
        run: |
          npm run build-hc
      # Setup sign & notarize
      - name: sign and notarize setup (macos only)
        if: ${{ runner.os == 'macOs' }}
        uses:  figleafteam/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.HBE_APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.HBE_APPLE_CERTIFICATE_PASS }}
      # Build installers and binaries
      - name: dist snapmail
        shell: bash
        env:
          WIN_CSC_LINK: ${{ steps.write_file.outputs.filePath }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
          APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
          APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DEBUG: electron-osx-sign*,electron-notarize*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist-build
      # upload installers and binaries
      - name: list builds
        run: ls
        working-directory: out
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "out/Snapmail-0.1.5.AppImage" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "out/Snapmail-0.1.5.dmg" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "bin/lair-keystore-linux" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "bin/holochain-linux" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "out/Snapmail Setup 0.1.5.exe" --clobber
          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "bin/lair-keystore-win.exe" --clobber
          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "bin/holochain-win.exe" --clobber
