
name: Cargo tests

on: [ push, pull_request ]

jobs:
  cargo_test:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: 1.55
         target: wasm32-unknown-unknown
     - run: ./scripts/dna-test.sh
